### ISSUE TITLE
Solve or document fix for rate limiting

### ISSUE THREAD

**Issue by rreusser** [scijs/packages#5]
I run into problems after the initial build. If there's a caching fix for this, then it need to be documented. If not, then some workaround might be necessary.

**Comment by hughsk** [comment]
The rate limits are a lot more manageable with stackgl's new packages site. Hitting the API and building the site are two separate steps, and better caching is in place. I believe it should be easier to fork too :)

**Comment by rreusser** [comment]
Last time I looked into things, it wasn't quite resolved how to maintain stackgl and scijs sites with the same ecosystem docs codebase. Any thoughts on whether this is easier now?

**Comment by hughsk** [comment]
It should be configurable using `config.js`, such that it's the only file requiring modification — PRs for further flexibility are definitely welcome though :)

**Comment by hughsk** [comment]
Oops, meant to include a link there: https://github.com/stackgl/packages/blob/master/config.js

**Comment by rreusser** [comment]
Thank! Looks promising. I still need to think about maintaining a scijs fork without constantly having to sort out merge conflicts for anything that's different for scijs.

Long shot: Given the config, is it at all possible to trivially pull the guts into an "ecosystem-docs" module or something and have anything that uses it call that?

**Comment by hughsk** [comment]
https://www.npmjs.com/package/ecosystem-docs :grin: This handles the data aggregation bit, which was easy to split it out.

The site itself less so... though it's only regularly updated for content, the styles/behaviours/etc. have been pretty stable since the rewrite (though tables may still need some love as you mentioned in #4). Merge conflicts might come up, but they would be months apart at the worst :)

**Comment by rreusser** [comment]
Ah, there it is. Yup. Thanks for the info. So that did come together. Nice work! Okay, that makes sense. Yeah, probably stable enough it makes sense to just fork, merge, and maintain. Thanks!

**Comment by rreusser** [comment]
Looks great! Will give a once over for stackgl content and probably just push it!

<img width="1025" alt="screen shot 2016-01-04 at 9 32 34 am" src="https://cloud.githubusercontent.com/assets/572717/12091636/42303e9e-b2c6-11e5-96f9-91a3ee47a101.png">

**Comment by hughsk** [comment]
Sweet! :grin:

**Comment by rreusser** [comment]
Live. Needs cleanup, but—and I don't have the google analytics to be sure—I don't think it gets much traffic :cry: so will clean up piece by piece. Thanks again!
